name: Caffine

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  daily-task:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/setup-node-js-environment
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run npm commands
        run: |
          npm run supa
          npm run mongo

      - name: Perform curl requests
        run: |
          curl "https://typer.onrender.com/socket.io/?EIO=4&transport=polling"
          curl "https://analytics.codabool.workers.dev/?secret=${{ secrets.ANALYTICS_SECRET }}"
